### model params
Model:
  in_channels: 1 #3
  out_channels: 1 #3
  model_channels: 128
  attention_resolutions: [16, 32]
  num_res_blocks: 3
  dropout: 0.1
  channel_mult: [1, 2, 4, 8]
  conv_resample: True
  num_heads: 4
  cond_dim: 1


### dataset params
TrainDataset:
  # Deciding which dataset to use, must be one of {'mnist', 'cifar', 'custom'}.
  dataset: "gedi"
  # If mnist and cifar datasets, whether to use the training set.
  #train: True
  # Folder of data sets. When `dataset = custom`, this parameter can be a list with different folders.
  # Then all images in the list with suffixes in `suffix` in the folder will be loaded.
  data_path: "./data/gedi/combined_df_train.pkl"
  
  # If mnist and cifar datasets, whether to download it.
  #download: True
  # If mnist dataset, image_size is [28, 28]. If cifar dataset, image_size is [32, 32]. If custom, specify as needed.
  #image_size: [ 32, 32 ]

  # If custom dataset, what is the mode of the image. must be one of {'RGB', 'L', 'CMYK'}.
  #mode: "RGB"
  # If custom dataset, decide what suffix to load for the image.
  #suffix: ["png", "jpg"]

  # parameters for torch.utils.data.DataLoader
  batch_size: 320 #64
  subset: 1
  #drop_last: True
  pin_memory: True
  num_workers: 8

ValDataset:
  dataset: "gedi"
  data_path: "./data/gedi/combined_df_val.pkl"
  # parameters for torch.utils.data.DataLoader
  batch_size: 128 #64
  subset: 1
  #drop_last: True
  pin_memory: True
  num_workers: 8

TestDataset:
  dataset: "gedi"
  data_path: "./data/gedi/combined_df_test.pkl"
  # parameters for torch.utils.data.DataLoader
  batch_size: 128 #64
  subset: 1
  #drop_last: True
  pin_memory: True
  num_workers: 8


### trainer params
Trainer:
  # sample time steps
  T: 1000
  beta: [0.0001, 0.02] #'cosine' #[0.0001, 0.02]


### callback params
Callback:
  # The save path for checkpoint.
  filepath: "./checkpoint/gedi_treecover_v4.pth"
  # Frequency of checkpoint saving.
  save_freq: 1

### train params
device: "cuda:0"
epochs: 6  # 1000
# Whether to continue training, True or False
consume: False
# If continue training, which checkpoint to load
consume_path: "./checkpoint/gedi_treecover_v4.pth"

### optimizer params
lr: 0.0002 #0.0002
